# Generated by Django 3.0.5 on 2020-10-05 16:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('form_slug_url', models.SlugField(help_text='a user non-friendly url', max_length=60, verbose_name='user non-friendly url')),
                ('Recipient', models.OneToOneField(help_text='User who will recieve feedback.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=100, verbose_name='Question')),
                ('forms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Form', verbose_name='Forms')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descibe', models.TextField(help_text='Explanation to be shown after the question has been answered.', max_length=200, verbose_name='Add Comment')),
                ('Rate', models.IntegerField(default=5, help_text='Please Rate out of 10 in support of your answer', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Rate(out of 10)')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Questions', verbose_name='Question')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
